namespace SoundShell {
    using System;
    using Terminal.Gui;
        
    public partial class Main : Terminal.Gui.Window {
        private Terminal.Gui.ColorScheme blackOnWhite;
        private Terminal.Gui.ColorScheme blueOnBlack;
        private Terminal.Gui.ColorScheme whiteOnBlue;
        private Terminal.Gui.ColorScheme greenOnBlack;
        private Terminal.Gui.Label labelTitle;
        private Terminal.Gui.Label label23;
        private Terminal.Gui.Label label2;
        private Terminal.Gui.Label labelFilename;
        private Terminal.Gui.Label label3;
        private Terminal.Gui.Label labelFileLength;
        private Terminal.Gui.Label label4;
        private Terminal.Gui.Label labelBitrate;
        private Terminal.Gui.Label label5;
        private Terminal.Gui.Label labelSmaplerate;
        private Terminal.Gui.Label label6;
        private Terminal.Gui.Label labelChannel;
        private Terminal.Gui.Label label12;
        private Terminal.Gui.Label label13;
        private Terminal.Gui.Label label14;
        private Terminal.Gui.Label label192;
        private Terminal.Gui.Label label21;
        private Terminal.Gui.Label label19;
        private Terminal.Gui.Label label20;
        private Terminal.Gui.Label label193;
        private Terminal.Gui.Label label22;
        private Terminal.Gui.Label label15;
        private Terminal.Gui.Label labelCurrentFrame;
        private Terminal.Gui.Label label17;
        private Terminal.Gui.Label labelCurrentMediaTime;
        private Terminal.Gui.FileDialog fileDialog;

        private void InitializeComponent() {
            this.labelCurrentMediaTime = new Terminal.Gui.Label();
            this.label17 = new Terminal.Gui.Label();
            this.labelCurrentFrame = new Terminal.Gui.Label();
            this.label15 = new Terminal.Gui.Label();
            this.label22 = new Terminal.Gui.Label();
            this.label193 = new Terminal.Gui.Label();
            this.label20 = new Terminal.Gui.Label();
            this.label19 = new Terminal.Gui.Label();
            this.label21 = new Terminal.Gui.Label();
            this.label192 = new Terminal.Gui.Label();
            this.label14 = new Terminal.Gui.Label();
            this.label13 = new Terminal.Gui.Label();
            this.label12 = new Terminal.Gui.Label();
            this.labelChannel = new Terminal.Gui.Label();
            this.label6 = new Terminal.Gui.Label();
            this.labelSmaplerate = new Terminal.Gui.Label();
            this.label5 = new Terminal.Gui.Label();
            this.labelBitrate = new Terminal.Gui.Label();
            this.label4 = new Terminal.Gui.Label();
            this.labelFileLength = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.labelFilename = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.label23 = new Terminal.Gui.Label();
            this.labelTitle = new Terminal.Gui.Label();
            this.fileDialog = new Terminal.Gui.FileDialog();
            this.blackOnWhite = new Terminal.Gui.ColorScheme();
            this.blackOnWhite.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackOnWhite.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackOnWhite.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackOnWhite.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blackOnWhite.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.whiteOnBlue = new Terminal.Gui.ColorScheme();
            this.whiteOnBlue.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.whiteOnBlue.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.blackOnWhite;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.None;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.labelTitle.Width = Dim.Fill(0);
            this.labelTitle.Height = 1;
            this.labelTitle.X = 0;
            this.labelTitle.Y = 0;
            this.labelTitle.Visible = true;
            this.labelTitle.ColorScheme = this.whiteOnBlue;
            this.labelTitle.Text = "SoundShell Version 1.0.0 -- Sibra-Soft 2026";
            this.labelTitle.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.labelTitle);
            this.label23.Width = 8;
            this.label23.Height = 1;
            this.label23.X = 1;
            this.label23.Y = 4;
            this.label23.Visible = true;
            this.label23.Text = "Media:";
            this.label23.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label23);
            this.label2.Width = 7;
            this.label2.Height = 1;
            this.label2.X = 3;
            this.label2.Y = 5;
            this.label2.Visible = true;
            this.label2.Text = "Filename";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.labelFilename.Width = 6;
            this.labelFilename.Height = 1;
            this.labelFilename.X = 21;
            this.labelFilename.Y = 5;
            this.labelFilename.Visible = true;
            this.labelFilename.ColorScheme = this.greenOnBlack;
            this.labelFilename.Text = ": No file loaded";
            this.labelFilename.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelFilename);
            this.label3.Width = 6;
            this.label3.Height = 1;
            this.label3.X = 3;
            this.label3.Y = 6;
            this.label3.Visible = true;
            this.label3.Text = "Length";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.labelFileLength.Width = 6;
            this.labelFileLength.Height = 1;
            this.labelFileLength.X = 21;
            this.labelFileLength.Y = 6;
            this.labelFileLength.Visible = true;
            this.labelFileLength.ColorScheme = this.greenOnBlack;
            this.labelFileLength.Text = ": -";
            this.labelFileLength.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelFileLength);
            this.label4.Width = 5;
            this.label4.Height = 1;
            this.label4.X = 3;
            this.label4.Y = 7;
            this.label4.Visible = true;
            this.label4.Text = "Bitrate";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.labelBitrate.Width = 15;
            this.labelBitrate.Height = 1;
            this.labelBitrate.X = 21;
            this.labelBitrate.Y = 7;
            this.labelBitrate.Visible = true;
            this.labelBitrate.ColorScheme = this.greenOnBlack;
            this.labelBitrate.Text = ": -";
            this.labelBitrate.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelBitrate);
            this.label5.Width = 6;
            this.label5.Height = 1;
            this.label5.X = 3;
            this.label5.Y = 8;
            this.label5.Visible = true;
            this.label5.Text = "Samplerate";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label5);
            this.labelSmaplerate.Width = 7;
            this.labelSmaplerate.Height = 1;
            this.labelSmaplerate.X = 21;
            this.labelSmaplerate.Y = 8;
            this.labelSmaplerate.Visible = true;
            this.labelSmaplerate.ColorScheme = this.greenOnBlack;
            this.labelSmaplerate.Text = ": -";
            this.labelSmaplerate.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelSmaplerate);
            this.label6.Width = 6;
            this.label6.Height = 1;
            this.label6.X = 3;
            this.label6.Y = 9;
            this.label6.Visible = true;
            this.label6.Text = "Channels";
            this.label6.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label6);
            this.labelChannel.Width = 5;
            this.labelChannel.Height = 1;
            this.labelChannel.X = 21;
            this.labelChannel.Y = 9;
            this.labelChannel.Visible = true;
            this.labelChannel.ColorScheme = this.greenOnBlack;
            this.labelChannel.Text = ": -";
            this.labelChannel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelChannel);
            this.label12.Width = 8;
            this.label12.Height = 1;
            this.label12.X = 1;
            this.label12.Y = 16;
            this.label12.Visible = true;
            this.label12.Text = "Controls:";
            this.label12.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label12);
            this.label13.Width = 6;
            this.label13.Height = 1;
            this.label13.X = 3;
            this.label13.Y = 17;
            this.label13.Visible = true;
            this.label13.Text = "ESC - ";
            this.label13.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label13);
            this.label14.Width = 3;
            this.label14.Height = 1;
            this.label14.X = 9;
            this.label14.Y = 17;
            this.label14.Visible = true;
            this.label14.ColorScheme = this.blueOnBlack;
            this.label14.Text = "Quit";
            this.label14.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label14);
            this.label19.Width = 6;
            this.label19.Height = 1;
            this.label19.X = 3;
            this.label19.Y = 18;
            this.label19.Visible = true;
            this.label19.Text = "F2  - ";
            this.label19.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label19);
            this.label20.Width = 3;
            this.label20.Height = 1;
            this.label20.X = 9;
            this.label20.Y = 18;
            this.label20.Visible = true;
            this.label20.ColorScheme = this.blueOnBlack;
            this.label20.Text = "Load Media File";
            this.label20.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label20);

            this.label193.Width = 6;
            this.label193.Height = 1;
            this.label193.X = 3;
            this.label193.Y = 20;
            this.label193.Visible = true;
            this.label193.Text = "P   - ";
            this.label193.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label193);
            this.label22.Width = 4;
            this.label22.Height = 1;
            this.label22.X = 9;
            this.label22.Y = 20;
            this.label22.Visible = true;
            this.label22.ColorScheme = this.blueOnBlack;
            this.label22.Text = "Pause";
            this.label22.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label22);
            
            this.label15.Width = 7;
            this.label15.Height = 1;
            this.label15.X = 1;
            this.label15.Y = Pos.AnchorEnd(2);
            this.label15.Visible = true;
            this.label15.Text = "Frame:";
            this.label15.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label15);
            this.labelCurrentFrame.Width = 5;
            this.labelCurrentFrame.Height = 1;
            this.labelCurrentFrame.X = 7;
            this.labelCurrentFrame.Y = Pos.AnchorEnd(2);
            this.labelCurrentFrame.Visible = true;
            this.labelCurrentFrame.ColorScheme = this.blueOnBlack;
            this.labelCurrentFrame.Text = "0";
            this.labelCurrentFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelCurrentFrame);
            this.label17.Width = 7;
            this.label17.Height = 1;
            this.label17.X = 16;
            this.label17.Y = Pos.AnchorEnd(2);
            this.label17.Visible = true;
            this.label17.Text = "Time:";
            this.label17.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label17);
            this.labelCurrentMediaTime.Width = 4;
            this.labelCurrentMediaTime.Height = 1;
            this.labelCurrentMediaTime.X = 22;
            this.labelCurrentMediaTime.Y = Pos.AnchorEnd(2);
            this.labelCurrentMediaTime.Visible = true;
            this.labelCurrentMediaTime.ColorScheme = this.blueOnBlack;
            this.labelCurrentMediaTime.Text = "0:00";
            this.labelCurrentMediaTime.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelCurrentMediaTime);

            this.fileDialog.Visible = false;
            this.fileDialog.AllowedFileTypes = [".mp3"];
            this.Add(fileDialog);
        }
    }
}
