name: Release

on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
  
      - name: Install dependencies
        run: dotnet restore
        
      - name: Test with .NET
        run: dotnet test
        
      - name: Extract version from tag
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION.0" >> $GITHUB_ENV
          
      - name: Publish
        run: > 
          msbuild.exe /target:publish
          /p:PublishProfile=FolderProfile.pubxml
          /p:ApplicationVersion=${{ env.VERSION }}
          /p:AssemblyVersion=${{ env.VERSION }}
                
      - name: Upload published output
        uses: actions/upload-artifact@v4
        with:
          name: SoundShell
          path: |
            ${{ github.workspace }}/bin/Publish/

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SoundShell
          path: app
          
      - name: Build installer
        run: makensis ./app/setup/sound_shell_setup.nsi
        
      - name: Upload setup file to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app/setup/sound_shell_windows_setup.exe
          asset_name: sound_shell_windows_setup.exe
          asset_content_type: application/exe
          
      - name: Delete used artifact(s)
        uses: geekyeggo/delete-artifact@v5
        with:
            name: SoundShell
